package com.myspace.demo1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Switch implements java.io.Serializable {

	static final long serialVersionUID = 1L;


	private java.lang.String assetType;

	private int asset_id;

	private java.lang.String attribute;

	private java.time.LocalDateTime dateTime;

	private java.lang.String site;

	private boolean value;

	public Switch() {
	}

	public java.lang.String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(java.lang.String assetType) {
		this.assetType = assetType;
	}

	public int getAsset_id() {
		return this.asset_id;
	}

	public void setAsset_id(int asset_id) {
		this.asset_id = asset_id;
	}

	public java.lang.String getAttribute() {
		return this.attribute;
	}

	public void setAttribute(java.lang.String attribute) {
		this.attribute = attribute;
	}

	public java.time.LocalDateTime getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(java.time.LocalDateTime dateTime) {
		this.dateTime = dateTime;
	}

	public java.lang.String getSite() {
		return this.site;
	}

	public void setSite(java.lang.String site) {
		this.site = site;
	}

	public boolean isValue() {
		return this.value;
	}

	public void setValue(boolean value) {
		this.value = value;
	}

	public Switch(java.lang.String assetType, int asset_id,
			java.lang.String attribute, java.time.LocalDateTime dateTime,
			java.lang.String site, boolean value) {
		this.assetType = assetType;
		this.asset_id = asset_id;
		this.attribute = attribute;
		this.dateTime = dateTime;
		this.site = site;
		this.value = value;
	}

}